### PR TITLE
fix(gradients): support for 'transparent' as a color stop

### LINKED ISSUE #64: Not recognising 'transparent' colour
Drawing a linear gradient which trails off to transparency using this code:
```js
    this.ctx = this.canv.current.getContext("2d");
    const gradient = this.ctx.createLinearGradient(x1, y1, x2, y2);
    gradient.addColorStop(0.0, this.state.colour);
    gradient.addColorStop(0.925, this.state.colour);
    gradient.addColorStop(1.0, "transparent");
    this.ctx.fillStyle = gradient;
    this.ctx.fillRect(x1, y1, w, h);
```

The above renders fine in Firefox, but is unable to build in the unit tests, caused by this error:
Screenshot 2020-04-08 at 13 10 05

After initially looking into it, I presume this is an issue to do with the [parse-color](https://www.npmjs.com/package/parse-color) module you are using, but it is quite old.

Is there a possibility of changing the library being used for this?

### PR DESCRIPTION
**Pull request by evanoc0**
No other modules I found could be used _plug'n'play_ here. It seems that the only value that parse-color doesn't handle correctly is `transparent`, so it can be handled especially

Some test cases that verify different color formats get handled correctly wouldn't hurt either.

resolves #64

### CODE REVIEW

**Comment by jtenner** [comment]
AFAIK `"transparent"` should also be a valid `fillStyle` and `strokeStyle`. Essentially, every call to `parseColor()` should check for `"transparent"`.

I am proposing to replace calls to `parseColor()` with another function that outputs `result.hex` to the appropriate value of `"transparent"` so that it works everywhere and results in a smaller codebase.

**Comment by jtenner** [comment]
Example output:

```ts
temp1
CanvasRenderingContext2D {canvas: canvas, globalAlpha: 1, globalCompositeOperation: "source-over", filter: "none", imageSmoothingEnabled: true, …}
temp1.fillStyle = "transparent"
"transparent"
temp1.fillStyle
"rgba(0, 0, 0, 0)"
```

**Comment by jtenner** [comment]
Another way to tackle this problem is to submit a pull request to the `parse-color` package, and fix support for `"transparent"` everywhere.

If perhaps they don't want to support this request, another option would be to fork `parse-color` and replace our usage of the module to a fork.

I will accept any of these solutions to get things working.

**Comment by evanoc0** [comment]
A module called [validate-color](https://github.com/dreamyguy/validate-color) can be used instead of parse-color, it validates colors by keyword, rgb[a] ,hex, and hsl[a] correctly.
There latest version of it on npm is currently missing it's lib, so I filed an issue and added the previous version, but when that is resolved it should be updated to latest.

**Comment by jtenner** [comment]
Wow this is great. Please give me a day to look over this and do a review.

File: __tests__/classes/CanvasRenderingContext2D.fillStyle.js [hunk 1]
```diff
@@ -11,7 +11,7 @@ beforeEach(() => {
 describe('fillStyle', () => {
   it('should parse a css color string \'blue\'', () => {
     ctx.fillStyle = 'blue';
-    expect(ctx.fillStyle).toBe('#00f');
+    expect(ctx.fillStyle).toBe('blue');
```
Comment (jtenner) [inline __tests__/classes/CanvasRenderingContext2D.fillStyle.js:14]: Please follow the specification. The browser returns `#00f`, and that's why this value is what it is.

File: src/classes/CanvasRenderingContext2D.js [hunk 2]
```diff
@@ -636,14 +618,7 @@ export default class CanvasRenderingContext2D {
 
   set fillStyle(value) {
     let valid = false;
-    if (typeof value === 'string') {
-      const result = parseCSSColor(value);
```
Comment (jtenner) [inline src/classes/CanvasRenderingContext2D.js:640]: See here. There's a reason why we inspected the output.

**Comment by evanoc0** [comment]
Further than validating them, to alter the format of provided colors to hex would require functionality more than `validate-color` offers so I'll go back to the drawing board on that.
I'll look at the [color-parse](https://www.npmjs.com/package/color-parse) module to see if it is suitable. It seems more up to date than `parse-color` and is inspired by it so should work similarly.

**Comment by jtenner** [comment]
Is it possible we could submit a pull request to the module we currently use? I bet the maintainer would appreciate it.

**Comment by jtenner** [comment]
If not, https://www.npmjs.com/package/color-rgba looks like it might be the module we need to use.

**Comment by evanoc0** [comment]
The original module hasn't been touched in 6 years, which doesn't inspire hope in me that an issue would be answered

`color-parse` and `color-rgba` come from the same organization and seem to both be part of a family of similar modules, so either should work equally well

**Comment by jtenner** [comment]
Yes. This looks like an opportunity to fork `parse-color`, maintain some fixes, publish it to npm with a different name. Looks like substack hasn't touched their software in a really long time.

**Comment by jtenner** [comment]
In fact it looks like it's just a wrapper for a set of functions provided by: https://github.com/Qix-/color-convert

`color-parse` is MIT license, so we can copy the source of the `color-parse/index.js` function directly into the project and use an updated version of `Qix-/color-convert` to convert the color values between each other.

**Comment by jtenner** [comment]
Upon further investigation it uses the https://github.com/colorjs/color-name/ package to generate colors. It uses only rgb values. Perhaps it's time to implement a proper spec compliant css color parser?

**Comment by jtenner** [comment]
image

This is much better. Sorry for being verbose. I am proposing to switch to `moo-color`. Please see the above output on how to parse the colors and return the correct string values.

**Comment by evanoc0** [comment]
The defintely seems like the best option, I'll try it out

**Comment by evanoc0** [comment]
I've read over the HTML canvas spec and updated this to follow the color-serialization rules faithfully.

Internally, the `_fillStack`, `_strokeStack`, and `_shadowStack` now take MooColor objects instead of strings and produce events with the value being those objects too. I take it those are only for testing and so that's ok, since the getters/setters produce the correct values?

File: __tests__/classes/CanvasRenderingContext2D.fillStyle.js [hunk 3]
```diff
@@ -11,12 +11,12 @@ beforeEach(() => {
 describe('fillStyle', () => {
   it('should parse a css color string \'blue\'', () => {
     ctx.fillStyle = 'blue';
-    expect(ctx.fillStyle).toBe('#00f');
+    expect(ctx.fillStyle).toBe('#0000ff');
```
Comment (jtenner) [inline __tests__/classes/CanvasRenderingContext2D.fillStyle.js:14]: Please assert that the fillStyle returns `"#00f"` here like the browser does instead of `"#0000ff"`. I believe that you can use the `"short"` parameter when using `moo-color`

File: __tests__/classes/CanvasRenderingContext2D.fillStyle.js [hunk 4]
```diff
@@ -11,12 +11,12 @@ beforeEach(() => {
...
   });
 
   it('should not parse invalid colors', () => {
     ctx.fillStyle = 'invalid!';
-    expect(ctx.fillStyle).toBe('#000');
+    expect(ctx.fillStyle).toBe('#000000');
```
Comment (jtenner) [inline __tests__/classes/CanvasRenderingContext2D.fillStyle.js:19]: Same critique, see above.

File: __tests__/classes/CanvasRenderingContext2D.fillStyle.js [hunk 5]
```diff
@@ -28,7 +28,7 @@ describe('fillStyle', () => {
     ctx.fillStyle = 'green';
     ctx.save();
     ctx.fillStyle = 'red';
-    expect(ctx.fillStyle).toBe('#f00');
+    expect(ctx.fillStyle).toBe('#ff0000');
```
Comment (jtenner) [inline __tests__/classes/CanvasRenderingContext2D.fillStyle.js:31]: Same critique, see above.

File: src/classes/CanvasRenderingContext2D.js [hunk 6]
```diff
@@ -97,7 +78,7 @@ export default class CanvasRenderingContext2D {
   }
 
   _directionStack = ['inherit'];
-  _fillStyleStack = ['#000'];
```
Comment (jtenner) [inline src/classes/CanvasRenderingContext2D.js:100]: Please don't use MooColor objects. Just use the strings like before.

Nit: Also, the code style for `jest-canvas-mock` is single quoted strings.

File: src/classes/CanvasRenderingContext2D.js [hunk 7]
```diff
@@ -111,11 +92,11 @@ export default class CanvasRenderingContext2D {
   _lineWidthStack = [1];
   _miterLimitStack = [10];
   _shadowBlurStack = [0];
-  _shadowColorStack = ['rgba(0, 0, 0, 0)'];
```
Comment (jtenner) [inline src/classes/CanvasRenderingContext2D.js:114]: Same critique. See above.

File: src/classes/CanvasRenderingContext2D.js [hunk 8]
```diff
@@ -659,7 +641,14 @@ export default class CanvasRenderingContext2D {
   }
 
   get fillStyle() {
-    return this._fillStyleStack[this._stackIndex];
```
Comment (jtenner) [inline src/classes/CanvasRenderingContext2D.js:662]: We should simply be able to return the stack value here.

File: src/classes/CanvasRenderingContext2D.js [hunk 9]
```diff
@@ -1282,22 +1271,26 @@ export default class CanvasRenderingContext2D {
...
-        const event = createCanvasEvent(
-          'shadowColor',
-          getTransformSlice(this),
-          { value: result },
-        );
-        this._events.push(event);
-      }
+      try { 
+        value = new MooColor(value);
+        this._shadowColorStack[this._stackIndex] = value;
```
Comment (jtenner) [inline src/classes/CanvasRenderingContext2D.js:1276]: Should be

```ts
this._shadowColorStack[this._stackIndex] = value.toHex('short');
```

File: src/classes/CanvasRenderingContext2D.js [hunk 10]
```diff
@@ -1373,13 +1366,14 @@ export default class CanvasRenderingContext2D {
...
     let valid = false;
     if (typeof value === 'string') {
-      const result = parseCSSColor(value);
-
-      if (result) {
+      try {
+        value = new MooColor(value);
         valid = true;
-        value = this._strokeStyleStack[this._stackIndex] = result;
+        this._strokeStyleStack[this._stackIndex] = value;
```
Comment (jtenner) [inline src/classes/CanvasRenderingContext2D.js:1372]: Should be

```ts
this._strokeStyleStack[this._stackIndex] = value.toHex('short');
```

File: src/classes/CanvasRenderingContext2D.js [hunk 11]
```diff
@@ -1282,22 +1271,26 @@ export default class CanvasRenderingContext2D {
...
+        getTransformSlice(this),
+        { value },
+      );
+      this._events.push(event);
     }
   }
 
   get shadowColor() {
-    return this._shadowColorStack[this._stackIndex];
+    const color = this._shadowColorStack[this._stackIndex];
```
Comment (jtenner) [inline src/classes/CanvasRenderingContext2D.js:1289]: We should be able to return the `shadowColorStack` value here just like above comments

File: __tests__/classes/CanvasRenderingContext2D.fillStyle.js (hunk 3 above)
Comment (evanoc0) [reply __tests__/classes/CanvasRenderingContext2D.fillStyle.js:14]: From the [spec](https://www.w3.org/TR/2dcontext/#serialization-of-a-color):
> if it has alpha equal to 1.0, then the string is a lowercase six-digit hex value, prefixed with a "#" character
> Otherwise, the color value has alpha less than 1.0, and the string is the color value in the CSS rgba() functional-notation format
Testing it in firefox, it also returns it in 6-digit notation rather than the shortened form

File: src/classes/CanvasRenderingContext2D.js (hunk 9 above)
Comment (jtenner) [reply src/classes/CanvasRenderingContext2D.js:1276]: I stand corrected. I am suggesting using a helper function that converts the `MooColor` to the correct string value used in the respective color stack.

```ts
// something like this?
function mooToColor(mooColorObject) {
  return  mooColorObject.getAlpha() === 1
    ? mooColorObject.toHex()
    : mooColorObject.toRGBA();
}
```

File: __tests__/classes/CanvasRenderingContext2D.fillStyle.js (hunk 3 above)
Comment (jtenner) [reply __tests__/classes/CanvasRenderingContext2D.fillStyle.js:14]: Yep! For some reason, this spec must have changed, or I overlooked it.

File: src/classes/CanvasRenderingContext2D.js (hunk 8 above)
Comment (jtenner) [reply src/classes/CanvasRenderingContext2D.js:662]: Reasoning: This is faster, otherwise accessing `fillStyle()` will cause MooColor to compute the string with each property access.

File: src/classes/CanvasRenderingContext2D.js (hunk 9 above)
Comment (jtenner) [reply src/classes/CanvasRenderingContext2D.js:1276]: Reasoning: We only need to parse the color once per set.

File: src/classes/CanvasRenderingContext2D.js (hunk 7 above)
Comment (evanoc0) [reply src/classes/CanvasRenderingContext2D.js:114]: resolved now

File: src/classes/CanvasRenderingContext2D.js (hunk 8 above)
Comment (evanoc0) [reply src/classes/CanvasRenderingContext2D.js:662]: solved this with a `serializeColor` method

File: src/classes/CanvasRenderingContext2D.js (hunk 11 above)
Comment (evanoc0) [reply src/classes/CanvasRenderingContext2D.js]: uses the new helper function `serializeColor`

File: src/classes/CanvasRenderingContext2D.js (hunk 6 above)
Comment (evanoc0) [reply src/classes/CanvasRenderingContext2D.js:100]: fixed this now 👍🏻 They get added to the stack as 6-digit hex colors and then re-parsed into a `MooColor` object for serialization

File: src/classes/CanvasRenderingContext2D.js (hunk 8 above)
Comment (evanoc0) [reply src/classes/CanvasRenderingContext2D.js:662]: `fillStyle()` will now either return the serialized color value, or the Gradient/Pattern object

File: src/classes/CanvasRenderingContext2D.js [hunk 12]
```diff
@@ -637,13 +625,14 @@ export default class CanvasRenderingContext2D {
...
     let valid = false;
     if (typeof value === 'string') {
-      const result = parseCSSColor(value);
-
-      if (result) {
+      try {
+        const result = new MooColor(value);
         valid = true;
-        value = this._fillStyleStack[this._stackIndex] = result;
+        value = this._fillStyleStack[this._stackIndex] = result.toHex();
```
Comment (jtenner) [inline src/classes/CanvasRenderingContext2D.js:631]: Suggesting to store the color as the correct string value here.

`serializeColor(result)`

File: src/classes/CanvasRenderingContext2D.js [hunk 13]
```diff
@@ -659,7 +648,11 @@ export default class CanvasRenderingContext2D {
   }
 
   get fillStyle() {
-    return this._fillStyleStack[this._stackIndex];
+    const color = this._fillStyleStack[this._stackIndex];
+    if(typeof color === 'string') {
+      return serializeColor(color);
+    }
+    return color;
```
Comment (jtenner) [inline src/classes/CanvasRenderingContext2D.js:655]: In this case, we don't need to do an `if` check if we always store the correct value on the stack.

File: src/classes/CanvasRenderingContext2D.js [hunk 14]
```diff
@@ -1282,22 +1275,22 @@ export default class CanvasRenderingContext2D {
...
-        const event = createCanvasEvent(
-          'shadowColor',
-          getTransformSlice(this),
-          { value: result },
-        );
-        this._events.push(event);
-      }
+      try { 
+        const result = new MooColor(value);
+        value = this._shadowColorStack[this._stackIndex] = result.toHex();
```
Comment (jtenner) [inline src/classes/CanvasRenderingContext2D.js:1280]: Suggesting to use `serializeColor(result)` here instead.

File: src/classes/CanvasRenderingContext2D.js [hunk 15]
```diff
@@ -1373,13 +1366,15 @@ export default class CanvasRenderingContext2D {
...
     if (typeof value === 'string') {
-      const result = parseCSSColor(value);
-
-      if (result) {
+      try {
+        const colorObject = new MooColor(value);
+        value = new MooColor(value);
         valid = true;
-        value = this._strokeStyleStack[this._stackIndex] = result;
+        value = this._strokeStyleStack[this._stackIndex] = colorObject.toHex();
```
Comment (jtenner) [inline src/classes/CanvasRenderingContext2D.js:1373]: Again, I think it would be a good idea to use `serializeColor()` here.

File: src/classes/CanvasRenderingContext2D.js [hunk 16]
```diff
@@ -1395,7 +1390,11 @@ export default class CanvasRenderingContext2D {
   }
 
   get strokeStyle() {
-    return this._strokeStyleStack[this._stackIndex];
+    const color = this._strokeStyleStack[this._stackIndex];
```
Comment (jtenner) [inline src/classes/CanvasRenderingContext2D.js:1393]: Again, I'm suggesting to return the value from the stack here to make it faster.

File: src/classes/CanvasRenderingContext2D.js (hunk 12 above)
Comment (jtenner) [reply src/classes/CanvasRenderingContext2D.js:631]: Reason: The browser parses the color with every `set` operation, and we would be doing exactly the same thing.

**Comment by evanoc0** [comment]
Just to ask, I'd like to include a test suite for the new function `serializeColor` to keep coverage at 100%. Is there a preferable way to make the function accessible to tests?

**Comment by jtenner** [comment]
I don't think this utility function is necessary, and we only need to snapshot and test the endpoint output. If perhaps you would like to test the function more, we can add more colors to the test suite, but it does look like everything is working as intended.

Another very good idea might just be to comment that function and state it's purpose.

**Comment by jtenner** [comment]
One last commit suggestion:

- Add a contributors section at the bottom of README.md
  - add @jtenner, @hustcc  and yourself to the list
- The changes involved here are backwards compatibile, but rewritten using a new module
  - add version 2.3.0 to the top of the list
  - add line item to changelog,md add "switched to `moo-color` for color parsing
